version: '2'

services:
  gocd:
    image: gocd/gocd-server:v17.9.0
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - /deployment/godata:/godata
      - /deployment/htpasswd:/htpasswd

  consul:
    image: consul
    volumes:
      - /deployment/consul:/tmp/consul
    ports:
      - "8500:8500"
    command: "consul agent -server -ui -bootstrap -data-dir /tmp/consul -bind=127.0.0.1 -client=0.0.0.0 -retry-join=0.0.0.0"
